app/main/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, SubmitField
from wtforms.validators import Required


class LoginForm(Form):
    """Accepts a nickname and a room."""
    name = StringField('Username', validators=[Required()])
    room = StringField('Room-ID', validators=[Required()])
    submit = SubmitField('Enter Chatroom')

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO
import os

socketio = SocketIO()


def create_app(debug=False):
    """Create an application."""

    # SETTING THE ENV VARIABLES
    os.environ['HOST'] = '192.168.1.9'
    os.environ['PORT'] = '5000'
    os.environ['SECRET_KEY'] = 'gjr39dkjn344_!67#'



    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = os.getenv("SECRET_KEY")

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    socketio.init_app(app)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

app/main/routes.py
from flask import session, redirect, url_for, render_template, request
from . import main
from .forms import LoginForm


@main.route('/')
def home():
    return render_template("index.html")


@main.route('/enter-room', methods=['GET', 'POST'])
def enter_room():
    """Login form to enter a room."""
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        return redirect(url_for('.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('enter-chat-room.html', form=form)


@main.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    name = session.get('name', '')
    room = session.get('room', '')
    if name == '' or room == '':
        return redirect(url_for('.enter_room'))
    return render_template('chat.html', name=name, room=room)

app/templates/chat.html
<html>
    <head>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
        <script type="text/javascript" charset="utf-8">
            var socket;
            $(document).ready(function(){
                socket = io.connect('http://192.168.1.9:5000/chat');
                socket.on('connect', function() {
                    socket.emit('joined', {});
                });
                socket.on('status', function(data) {
                    $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                socket.on('message', function(data) {
                    $('#chat').val($('#chat').val() + data.msg + '\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
                        socket.emit('text', {msg: text});
                    }
                });
            });
            function leave_room() {
                socket.emit('left', {}, function() {
                    socket.disconnect();

                    // go back to the login page
                    window.location.href = "{{ url_for('main.enter_room') }}";
                });
            }
        </script>
        <title>Brainstorming - Room - {{ room }}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    </head>

    <style type="text/css">
        body {
            background-color: #212121;
            color: white;
            background-image: url("{{ url_for('static', filename='bg1.png') }}");
            background-size: cover;
        }

        ::-webkit-scrollbar {
          width: 5px;
        }
        ::-webkit-scrollbar-track {
          background: #212121;
        }
        ::-webkit-scrollbar-thumb {
          background: #888;
          border-radius: 2px;
        }
        ::-webkit-scrollbar-thumb:hover {
          background: #555;
        }


    </style>

    <body>

        <!-- NAV -->
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgba(2, 2, 2, 0.3)">
          <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Brainstorming</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{{ url_for('main.enter_room') }}">Enter A Room</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        <br><br><div class="chat-msgs" style="text-align: center; padding: 10px;" >
            <textarea id="chat" cols="80" rows="20" style="padding: 20px; border-radius: 20px;
             background-color: rgba(33, 33, 33, .9); border: none; outline: none; color: white; resize: none;
             border-top-right-radius: 0px; border-bottom-right-radius: 0px;" readonly></textarea>
        </div>
        
        <div class="sendmsg" style="text-align: center;">
            <input id="text" size="80" style="border-radius: 5px; padding: 10px; border: none; outline: none; 
            background-color: rgba(33, 33, 33, 0.9); color: white;" placeholder="Enter your message here"><br><br>
        </div>
        <p style="text-align: center;" onclick="leave_room();">
            <button class="btn btn-outline-danger">Leave this room</button>
        </p>
        <br><br><br>
    </body>
</html>

app/templates/enter-chat-room.html
<!DOCTYPE html>
<html>
<head>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Brainstorming - Enter A Chat Room</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    </head>
</head>

<style type="text/css">
	body {
	    background-color: #212121;
	    color: white;
	    background-image: url("{{ url_for('static', filename='bg1.png') }}");
	}

	.parallax {
	  height: 650px;
	  background-attachment: fixed;
	  background-position: center;
	  background-repeat: no-repeat;
	  background-size: cover;
	}

	.jumbotron {
		background-color: rgba(33, 33, 33, 0.5);
	}

	input {
		width: 75%;
		outline: none;
		border: none;
		outline: none;
		padding: 10px;
		border-radius: 10px;
	}
	.input {
		text-align: left;
	}

	.btn {
		width: auto;
		padding: 10px;
	}

	.button-holder {
        display: flex;
	   	justify-content: center;
	   	align-items: center;
	   	height: 0px;
	   	margin-top: 50px;
    }

    .form-control {
		width: 75%;
		margin: auto;
	}

	::-webkit-scrollbar {
	  width: 5px;
	}
	::-webkit-scrollbar-track {
	  background: #212121;
	}
	::-webkit-scrollbar-thumb {
	  background: #888;
	  border-radius: 2px;
	}
	::-webkit-scrollbar-thumb:hover {
	  background: #555;
	}
</style>

<body>

	<!-- NAV -->
	<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgba(2, 2, 2, 0.3)">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{{ url_for('main.home') }}">Brainstorming</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNav">
	      <ul class="navbar-nav">
	        <li class="nav-item">
	          <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link active" href="{{ url_for('main.enter_room') }}">Enter A Room</a>
	        </li>
	      </ul>
	    </div>
	  </div>
	</nav>

	<br>
	<br>
	<div class="container">
		<div class="jumbotron" style="background-color: rgba(33, 33, 33, 0.5); padding: 50px; border-radius: 25px;
			box-shadow: 5px 5px 50px #212121">
			<form method="POST">
			    {{ form.hidden_tag() }}
			    {{ form.name.label }}<br><div class="input">{{ form.name() }}</div> {% for error in form.name.errors %}{{ error }}{% endfor %}<br><br>
			    {{ form.room.label }}<br><div class="input">{{ form.room() }}</div> {% for error in form.room.errors %}{{ error }}{% endfor %}<br><br>
			    <div class="form-group btn-holder">
			    	{{ form.submit(class="btn btn-outline-primary btn-sm") }}
				</div>
			</form>
		</div>
	</div>
</body>
</html>

app/templates/index.html
<html>
    <head>
        <title>Brainstorming</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    </head>

    <body>
        
        <!-- NAV -->
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgba(2, 2, 2, 0.3)">
          <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Brainstorming</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link active" href="{{ url_for('main.home') }}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.enter_room') }}">Enter A Room</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        <!-- CAROUSEL -->
        <div id="carousel" class="carousel slide" data-bs-ride="carousel">
          <ol class="carousel-indicators">
            <li data-bs-target="#carousel" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#carousel" data-bs-slide-to="1"></li>
            <li data-bs-target="#carousel" data-bs-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{{ url_for('static', filename='brainstorming.jpg') }}" class="d-block w-100" alt="...", style="height: 100vh; filter: brightness(0.5);">
              <div class="carousel-caption d-none d-md-block">
                <h5>Welcome To Brainstorming.</h5>
                <p>A Simple, Efficient, Fast, Easy, Sleek and Modern, NO SIGNUPs REQUIRED! free to use site.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{{ url_for('static', filename='sta.png') }}" class="d-block w-100" alt="...", style="height: 100vh; filter: brightness(0.5);">
              <div class="carousel-caption d-none d-md-block">
                <h5>Using State of The Art.</h5>
                <p>Using the latest and greatest version of Bootstrap 5 for CSS and Fast and reliable Framework Flask for the Back-end with the state of the art AES encryption algorithm used by the US Government to protect your data and privacy.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{{ url_for('static', filename='world.png') }}" class="d-block w-100" alt="...", style="height: 100vh; filter: brightness(0.5);">
              <div class="carousel-caption d-none d-md-block">
                <h5>Discuss, Chat And Hangout With Others!</h5>
                <p>Brainstorming is connected throughout the globe and any one can come and discuss, chat, hangout with others</p>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carousel" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carousel" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </a>
        </div>


        <div id="about">
          <br><br>
          <div>
            <h2 style="text-align: center;">What is Brainstorming?</h2><br>
            <p style="text-align: center;" class="container">"Brainstorming is a group creativity technique by which efforts are made to find a conclusion for a specific problem by gathering a list of ideas spontaneously contributed by its members." And we also implment a similar this website is built for people who are creative or are working in groups to find ideas and simply just to hang out with others, Brainstorming is connected throughout the world so that means that you can chat with anyone in the world when they are online.</p>
          </div>
          <br><br>
          <div class="parallax" style="background-image: url({{ url_for('static', filename='bg1.png') }})"></div>

          <br><br>
          <div>
            <h2 style="text-align: center;">What we use?</h2><br>
            <p style="text-align: center;" class="container">We use the state of the art components used by Big Tech Companies like Google, Microsoft, Apple. We use Flask a Python's backend framework to manage user's and their messages, we use CSS3 and the latest version of Bootstrap v5.0 and Vanilla JS to ensure the best web experience for our users, and finally for your security we use the absolutely impenetrable Advanced Encryption Standard 256 encryption algorithm, it has 9 * 10^78 possible combinations if you use Tianhe-2(MilkyWay-2) the world's most powerful computer it would take millions of year to crack your privacy.</p>
          </div>
          <br><br>
          <div class="parallax" style="background-image: url({{ url_for('static', filename='bg2.jpg') }})"></div>

          <br><br>
          <div>
            <h2 style="text-align: center;">Join Today!</h2><br>
            <p style="text-align: center;" class="container">What are you waiting for? Join Brainstorming Today and chat, discuss, find solutions, hang out with people through out the world!</p>
            <hr>
            <p style="text-align: center;">2021(C) Copyright, Made with <span style="color: red;">&#x2764;</span> By Aryan Mishra.</p>
          </div>
          <br><br>
        </div>
    </body>
</html>